[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "deny"
        X-XSS-Protection = "1"
        Expect-CT = "max-age=86400, enforce"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy = "no-referrer"
        Cross-Origin-Opener-Policy = "same-origin"
        Cross-Origin-Resource-Policy = "same-origin"
        Cross-Origin-Embedder-Policy = "require-corp"
        Access-Control-Allow-Origin = "https://brendanhoeflich.netlify.app"
        Public-Key-Pins = "pin-sha256='GRAH5Ex+kB4cCQi5gMU82urf+6kEgbVtzfCSkw55AGk=";max-age=15768000; includeSubDomains'"
        
        Strict-Transport-Security = '''
            max-age=31557600;
            includeSubDomains;
            preload
        '''
        
        Permissions-Policy = '''
            camera=(), 
            microphone=(), 
            geolocation=(),
            accelerometer=(),
            battery=(),
            document-domain=(),
            gyroscope=(),
            magnetometer=(),
            usb=()
        '''
        
        Content-Security-Policy = '''
            script-src 'none';
            script-src-attr 'none';
            script-src-elem 'none';
            worker-src 'none';
            navigate-to 'none';
            form-action 'none';
            media-src 'none';
            object-src 'none';
            
            require-trusted-types-for 'script';
        '''
