[[headers]]
    for = "/*"
    [headers.values]
        X-Frame-Options = "deny"
        X-XSS-Protection = "1"
        Expect-CT = "max-age=86400, enforce"
        X-Content-Type-Options = "nosniff"
        Referrer-Policy = "no-referrer"
        Cross-Origin-Opener-Policy = "same-origin"
        Cross-Origin-Resource-Policy = "same-origin"
        Cross-Origin-Embedder-Policy = "require-corp"
        Access-Control-Allow-Origin = "https://brho.netlify.app"
        X-Permitted-Cross-Domain-Policies = "none"
        
        Strict-Transport-Security = '''
            max-age=31557600;
            includeSubDomains;
            preload
        '''
        
        Permissions-Policy = '''
            ambient-light-sensor=(),
            autoplay=().
            display-capture=(),
            gamepad=(),
            publickey-credentials-get(),
            payment=(),
            usb=(),
            camera=(), 
            microphone=(), 
            geolocation=(),
            accelerometer=(),
            battery=(),
            document-domain=(),
            gyroscope=(),
            magnetometer=(),
            usb=()
        '''
        
        Content-Security-Policy = '''
            script-src 'nonce-YXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5eXl5b2hoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhoaGhlZWVlZWVlZWVleXl5eXl5b2hhaGFoYWhhaGFoYWhhc2lsbGZlbGxhY3JhY2t0aGlz';
            base-uri 'none';
            worker-src 'none';
            manifest-src 'none';
            navigate-to 'none';
            form-action 'none';
            media-src 'none';
            object-src 'none';
            
            require-trusted-types-for 'script';
        '''
